spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/realCustomer
    username: root
    password: root
  jpa:
    show-sql: true

  h2:
    console:
      enabled: false
server:
  port: 8080