server:
  port: 8080

spring:
  kafka:
    bootstrapAddress:
      localhost:9092

  profiles:
    active: test
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    show-sql: true

  h2:
    console:
      enabled: true







message:
  topic:
    name:  baeldung


partitioned:
  topic:
    name: partitioned